### ISSUE TITLE
java.lang.IllegalArgumentException: java.nio.charset.CharsetICU[UTF-8] when printing lyrics

### ISSUE THREAD

**Issue by DimitrisStaratzis** [LowLevelSubmarine/GeniusLyricsAPI-not-official-#1]
The above exception is thrown when trying to print lyrics.

**Comment by LowLevelSubmarine** [comment]
Can you give me the search term you entered and the result you chose to print? So that I can repoduce the failure. Thx for using my api btw ;)

**Comment by DimitrisStaratzis** [comment]
Hello, no matter what terms I use, the error remains. 
This is the line that generates the problem:

Scanner scanner = new Scanner(connection.getInputStream(), StandardCharsets.UTF_8.toString());

inside parseLyrics method.

Maybe instead of StandardCharsets.UTF_8.toString() use "UTF-8".

**Comment by LowLevelSubmarine** [comment]
Closing this issue 2 years later, fixed it now with e926188d86be4ef3b78bec382752d28e3d6ecf06
